// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY

                    const filterValues = {
  "years": [
    2025,
    2024,
    2023,
    2022
  ],
  "months": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12
  ],
  "categories": [
    "Baby Care",
    "Fabric & Home Care",
    "Grooming",
    "Oral Care",
    "Fem Care",
    "Health Care",
    "Hair Care",
    "Personal Care (GIL)",
    "Personal Care (OS)",
    "Skin Care",
    "Aircare",
    "Appliances"
  ],
  "brands": [
    "Pampers",
    "Tide",
    "Gillette Presto Intl",
    "Guard",
    "Satin Care",
    "Wilkinson Sword",
    "ORAL B",
    "Whisper",
    "VCD",
    "Vaporub",
    "Ariel Liquid",
    "H&S",
    "Pantene",
    "7 O Clock",
    "7 O Clock PII",
    "Gillette Mach3",
    "Gillette Vector Plus",
    "Venus",
    "Gillette",
    "Gillette Series",
    "BabyRub",
    "Inhaler",
    "Old Spice",
    "Ariel",
    "Olay",
    "Fusion",
    "Mach-3 Turbo",
    "Vector3",
    "Wilman",
    "Vicks",
    "Winner",
    "AmbiPur",
    "Vaporub Xtra Strong",
    "Gillette Satin Care",
    "Pampers Baby Wipes",
    "Skinguard",
    "Fusion PC",
    "Liners",
    "HERBAL ESSENCES",
    "Gillette Labs",
    "Action 500",
    "Braun",
    "Vicks 3in1",
    "Pantene Oil Replacement",
    "King C Gillette",
    "Gillette Sport",
    "Gillette Sensor Excel"
  ],
  "brandforms": [
    "Pampers Pants-LCPs (1s-2s-4s)",
    "Tide Base Bags",
    "Tide FreshClean",
    "GPI",
    "Guard Cart",
    "Guard Razor",
    "Guard3 Carts",
    "S Other Disp",
    "Wilkson DE Blades",
    "OB 3in1 GP card",
    "OB 4in1 Natural Card",
    "OB Kids Top",
    "Whisper Choice",
    "Whisper Choice Ultra",
    "VCD",
    "Vaporub",
    "Ariel Matic Liquid",
    "Tide Bar",
    "H&S Bottles",
    "H&S Sachets",
    "Pantene Bottles",
    "Pantene Sachets",
    "7 DE Rzr",
    "7 Other System Cart",
    "Mach-3 Cart",
    "Mach-3 Rzr",
    "SP Blades",
    "Vector Cart",
    "Vector Rzr",
    "Venus Razor",
    "OB CD Bac Fight",
    "OB Kids",
    "OB Kids Low",
    "OB Prohealth New",
    "OB Sensitive",
    "Oral Care Spl",
    "Gillette Foam",
    "Gillette Shave Brush",
    "Gillette Shaving Crm",
    "Guard Cream",
    "Tube Shave Gel",
    "Whisper Ultra",
    "Whisper Ultra Soft",
    "BabyRub",
    "Inhaler",
    "Old Spice After Shave",
    "Old Spice Deodorants",
    "Old Spice Shaving Cream",
    "Active Baby",
    "Pampers Imax",
    "Pampers Pants-Big Packs",
    "Pampers Pants-Mid Packs",
    "Ariel PerfectWash",
    "Pantene Conditioner Bottles",
    "AP Cream",
    "Natural Aura Cream",
    "RG Cream",
    "Total Effects Cleanser",
    "Total Effects Cream",
    "Guard3 Rzr",
    "OB Complete Clean",
    "OB WS Shiny Clean",
    "Whisper Thick",
    "Premium Pants",
    "Ariel Base Bags",
    "H&S 2-in-1 Bottle",
    "Fusion Raz",
    "Turbo Mach-3 Cart",
    "Vector3 Razor",
    "Venus Cart",
    "OB Cav Def Charcoal",
    "After Shave Splash",
    "Old Spice After Shave Atomizer",
    "Ariel New Matics",
    "Ariel Canister",
    "Mach-3 Start Cart",
    "WR Cream",
    "Fusion Cart",
    "W Other System Cart",
    "PureZZZS",
    "Pantene 2in1 Bottles",
    "Gillette 4in1 GP Pack",
    "Vector3 Cart",
    "Turbo Mach-3 Rzr",
    "Winner DE Blades",
    "AmbiPur Air Effects",
    "Olay Super Serums",
    "Tide Liquid",
    "Other System Rzr",
    "Vaporub Xtra Strong",
    "Ariel Bucket",
    "Tide Bucket",
    "OB 123 Clove",
    "OB 123 Neem",
    "OB 3in1 Herbs",
    "Venus Disposable",
    "SC Series Foam & Gel",
    "AmbiPur Car Gel",
    "Tide Naturals",
    "AmbiPur Car Starters",
    "Pampers Wipes",
    "OB 123 Natural 3in1",
    "Venus Snap",
    "OB Prohealth",
    "Moisturizing Cream",
    "Olay Collagen",
    "Olay Retinol",
    "Olay Whips",
    "SS Blades",
    "Mach-3 Start Rzr",
    "SkinGuard Cart",
    "H&S Conditioner",
    "Power Oral Care",
    "AmbiPur Home Gel",
    "Olay Luminous",
    "Natural White Cream",
    "G Series Foam & Gel",
    "Olay AHA",
    "Fusion Gel",
    "Whisper Liners",
    "OB ProhealthN6+1Free",
    "AmbiPur Car Refills",
    "ProGlide Flexbal Rzr",
    "OB Shiny Clean",
    "Olay Eyes",
    "OB Shiny Clove",
    "Ariel PODS",
    "Mach3 Carts eC",
    "Mach3 H+2 eC",
    "ProGlide Cart",
    "Mosquito Guard Pants",
    "Tide PODS",
    "Tide Ultra Machine",
    "Herbal Conditioner",
    "Herbal Shampoo",
    "Fusion Carts eC",
    "Gillette Heated Razor",
    "M3T Carts eC",
    "Presto3",
    "Proglide Carts eC",
    "Oral-B Manual",
    "SkinGuard Raz",
    "OB Shiny Tulsi",
    "Action 500",
    "Moisturizing Lotion",
    "OB POC Handle",
    "Braun Beard Trimmer",
    "Braun Body Groomer",
    "Braun Epilator",
    "Braun Face Trimmer",
    "Braun Multi Grooming Kit",
    "OB POC Refill",
    "Braun Shavers",
    "Vicks",
    "Vicks 3in1",
    "Fusion Gift Pack",
    "7 Other Disp",
    "Guard Gel",
    "Gill Super Saver Pack",
    "OB Fresh Clean Chrcl",
    "OB Cavity Defense",
    "Olay Masks",
    "H&S Conditioner Sachets",
    "Pantene Conditioner Sachets",
    "OB WS Cavity Defense",
    "OB WS FreshCln Neem",
    "OB WS Fresh Clean",
    "Pantene OR",
    "Ariel Base Rs. 10",
    "Guard Foam",
    "Ariel Sachets",
    "OB WS CD Bac Fight",
    "OB Shiny Clean Promo",
    "Pampers Preemies",
    "KCG",
    "OB Fresh Clean",
    "Natural White Cleanser",
    "TE FW Cream",
    "OB Cav DefBlack",
    "OB Classic Super Clean",
    "Gillette 5 Sport",
    "Excel Cart",
    "Excel Razor",
    "DCL Facewash",
    "Gillette 3in1 GP Pack",
    "OB 3in1 Combo Pk",
    "Braun IPL"
  ],
  "branches": [
    "NORTH",
    "NORTH_WS",
    "ARAMBAGH",
    "ASANSOL",
    "BAGHAJATIN",
    "BAHARAMPUR",
    "BAJKUL",
    "BANKURA",
    "BARASAT",
    "BASIRHAT",
    "BELDA",
    "BIRPARA",
    "BISHNUPUR",
    "BALURGHAT",
    "BALLYGUNJ",
    "BOLPUR",
    "BONGAON",
    "BISHNUPUR2",
    "BURDWAN",
    "CANNING",
    "CHANDANNAGAR",
    "CONTAI",
    "COOCHBEHAR",
    "DASPUR",
    "DURGAPUR",
    "GHATAKPUKUR",
    "HABRA",
    "HINDMOTOR",
    "HOWRAH",
    "ISLAMPUR",
    "JALPAIGURI",
    "JANGALPUR",
    "JALANGI",
    "JOKA",
    "JOYNAGAR",
    "KAKDWIP",
    "KALYANI",
    "KATWA",
    "KHARAGPUR",
    "KHILA",
    "KALNA",
    "KRISHNANAGAR",
    "MAHESHTALA",
    "MALDA",
    "MEDINAPUR",
    "NAZIRPUR",
    "NAGRAKATA",
    "PALASSEY",
    "PANDAVESWAR",
    "PURULIA",
    "RAGHUNATHGANJ",
    "RAIGANJ",
    "RAJARHAT",
    "RANAGHAT",
    "RANIHATI",
    "SAMSI",
    "SHIBANIPUR",
    "SHYAMNAGAR",
    "SILIGURI",
    "SILIGURI_MR",
    "SONARPUR",
    "SIKKIM_SUBD",
    "SURI",
    "TAMLUK",
    "TARAKESHWAR",
    "ULUBERIA",
    "Akui",
    "Bijanbari",
    "Dalkhola",
    "Darjeeling",
    "Dhola",
    "Dhulian",
    "Farakka",
    "Ranipool",
    "Gangtok",
    "Gangtok-Tibet Road",
    "Garchumuk",
    "Ghoom",
    "Gosaba",
    "Gotan",
    "Geyzing",
    "Jamalpur",
    "Jhalda",
    "Jorethang",
    "Kaliaganj",
    "Kamakshyaguri",
    "Khatra",
    "Kalimpong",
    "Kurseong",
    "Manbazar",
    "Mathabhanga",
    "Mirik",
    "Melli",
    "Naxalbari",
    "Pakuahat",
    "Raghunathpur",
    "Raipur",
    "Ravangla",
    "Raidighi",
    "Rangpo",
    "Sagar",
    "Sehara",
    "Shyampur",
    "Sitalkuchi",
    "Sandeshkhali",
    "Soreng",
    "Sukhiapokhri",
    "Bishnupur",
    "Katwa"
  ],
  "zms": [
    "Somnath Banerjee",
    "Sudip Mukherjee",
    "Tarun Das",
    "Debraj Roy",
    "Pradip Debnath"
  ],
  "sms": [
    "Biswajit Bardhan",
    "Satish Kumar Singh",
    "Tarak Sasmal",
    "Debraj Roy",
    "Sumit Mukherjee",
    "Paltu Saha",
    "Parijat Sarkar",
    "Somnath Banerjee",
    "Ashok Yadav"
  ],
  "bes": [
    "Biswajit Bardhan",
    "Surajit Saha",
    "Debnath Ghosh",
    "Atanu Mukherjee",
    "Tushar Kanti Ghosh",
    "Dibakar Debnath",
    "Rantu Das",
    "Nabin Pradhan",
    "Subhasish Mondal",
    "Sankar Ghosh",
    "Atanu Ghosh",
    "Somnath Banerjee",
    "Santosh Kumar Sah",
    "Sudip Bhadra",
    "Kumaresh Ghosh",
    "Rishi Das",
    "Lakshman Bera",
    "Srikanta Samanta",
    "Ashok Sadhukhan",
    "Sandeep Ram",
    "Apu Paul",
    "Mritunjoy Singh",
    "Sukhen Dey",
    "Satish Singh",
    "Ashok Yadav_SM",
    "Prasenjit Singha Roy",
    "Ashok Yadav"
  ],
  "channels": [
    "Cash&Carry",
    "Large A Beauty",
    "Large A Pharmacy",
    "Large B Pharmacy",
    "Medium Beauty",
    "Medium Pharmacy",
    "New Pharmacy",
    "Small A Beauty",
    "Small A Pharmacy",
    "eCommerce",
    "Large A Traditional",
    "Large B Traditional",
    "Medium Traditional",
    "New Traditional",
    "Small A Traditional",
    "Small B Traditional",
    "Small C Traditional",
    "Hyper",
    "MM 1",
    "MM 2",
    "Super",
    "WS Beauty & Pharmacy",
    "WS Traditional",
    "Speciality",
    "Semi WS Traditional",
    "Semi WS Beauty & Pharmacy",
    "WS Feeder Traditional",
    "WS Feeder Beauty",
    "WS Feeder Pharmacy",
    "WS Non-Feeder Traditional",
    "WS Non-Feeder Beauty",
    "WS Non-Feeder Pharmacy",
    "Semi WS Beauty",
    "Semi WS Pharmacy",
    "Small D Traditional",
    "Small D Beauty",
    "Small D Pharmacy",
    "New Beauty",
    "MINIMARKET",
    "CONVENIENCE"
  ],
  "broadChannels": [
    "MR",
    "Large+Medium",
    "Small",
    "Ecom",
    "Wholesale"
  ],
  "shortChannels": [
    "MR",
    "Large A",
    "Large B",
    "Small A",
    "Medium",
    "New",
    "Ecom",
    "Small B",
    "Small C",
    "MM",
    "WS-Platinum",
    "WS-Gold",
    "WS-Silver",
    "Speciality"
  ]
} as const;

                    export default filterValues;
                    