name: Force Vercel Deploy

on:
  push:
    branches:
    - main # or your deploy branch

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update deploy trigger file
      run: |
        echo "Last deploy trigger: $(date -u)" > .vercel-deploy-trigger.txt

    - name: Commit & push as owner
      run: |
        git config user.name "${{ secrets.OWNER_NAME }}"
        git config user.email "${{ secrets.OWNER_EMAIL }}"
        git add .vercel-deploy-trigger.txt
        git commit -m "chore: trigger vercel deploy [ci skip]" || echo "No changes"
        git push origin main
      env:
        GIT_AUTHOR_NAME: "${{ secrets.OWNER_NAME }}"
        GIT_AUTHOR_EMAIL: "${{ secrets.OWNER_EMAIL }}"
        GIT_COMMITTER_NAME: "${{ secrets.OWNER_NAME }}"
        GIT_COMMITTER_EMAIL: "${{ secrets.OWNER_EMAIL }}"
        GIT_ASKPASS: /dev/null
        GIT_TERMINAL_PROMPT: 0
        GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
